#!/bin/bash
/usr/sbin/sendmail $1 << EOF
From: TBG Moderator <tbg-moderator@asciiking.com>
To: $1
Subject: TBG will be back soon with your regular ship still in progress
Content-Type: text/plain; charset="7bit"
Comments: Using sendmail
Organization: ASCII King Games
X-Mailer: script shell from njudge 1.7.6
X-Njudge: NO

Greetings,

I'm sorry to say that some of my changes went much more awry than I hithertofore expected. As a consequence, everyone was restarted. This obviously cannot be allowed to stand and it won't. You'll be able to pick up with your ship as it was last turn once I am done.

I will restore the server to the most recent turn possible and run this turn again, at which point I will let you know when the next turn will run.

With apologies,
Chris Babcock
5335 N 19th Ave #803
Phoenix, AZ USA 85015
602-859-1689

